server:
  port: 9001
spring:
  redis:
    port: 6379
    host: localhost
  application:
    name: eat
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eat
    username: root
    password: 798868370
  servlet:
    multipart:
      max-file-size: 200MB
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
##  global-config:
##    db-config:
##      id-type: ID_WORKER
#
#
zhx:
  filePath: /Users/nexta1/Documents/java/eat/src/main/resources/files/
#
